baseURL = "https://tushroy.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Tushar Roy Â· Landing Page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Tushar Roy"
  email = "android@codemonkey.in"
  description = "Landing Page"
  bio = "Tech Savvy. \nSoftware Engineer."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/tushroy"
    linkedin = "https://www.linkedin.com/in/tushroy"
	facebook = "https://facebook.com/tushar.se"
    twitter = "https://twitter.com/roytush"
	tumblr = "https://blog.codemonkey.in"
	
